### ISSUE TITLE
大佬求教

### ISSUE THREAD

**Issue by mrfuturman** [ToBeDefined/TLocationPlugin#10]
/TLocationPlugin/RunScript/inject_app_icon.py", line 202, in <module>
    iPadOldCFBundlePrimaryIcon = plist_info["CFBundleIcons~ipad"]["CFBundlePrimaryIcon"]
KeyError: 'CFBundlePrimaryIcon'

以前好好的，现在怎么跳出这个

**Comment by ToBeDefined** [comment]
修改了增加了判断，我没办法测试，你可以试下，如果还有问题可以把这几行注释也行
