### ISSUE TITLE
您好，感谢企业微信可用了，您尝试过钉钉么

### ISSUE THREAD

**Issue by CHparis** [ToBeDefined/TLocationPlugin#7]
您好，我在直接编译钉钉的时候，打卡定位没有什么问题，但是点击打卡的时候会提示【公司不允许使用虚拟定位软件。为防止信息被窃取，请卸载虚拟定位软件。】的提示，请问这个有办法可以绕开么？

**Comment by ToBeDefined** [comment]
钉钉做了签名验证，只要进行了重签名，就算不注入任何库，也会被标记为虚拟定位
